### PR TITLE
Updated Lab 15 to fix a few issues

### PR DESCRIPTION
**Pull request by yashints**
## Related Issue

**Link related Github Issue** 🢂 Fixing #397 and #396 

## Checklist 
Mark completed with "x" between brackets, "[x]", or checking the box once the PR is created:
- [x] Has related GitHub Issue 💥 [Create Issue](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#reporting-issues) 📝
- [x] Tested it
- [x] Read the PR collaboration guide 👓 [Collaboration Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#pull-requests) 📝

Changes proposed in this pull request:

- Added the steps to create the resource group
- Added the name of the storage account parameter to the bicep module

### CODE REVIEW

**Comment by unaihuete93** [comment]
Looks good for me, but not the MTT Lead anymore :) @petender @fimdim @lauraAlvEl I think this PR is ready for merge ;)

**Comment by fimdim** [comment]
@unaihuete93 same here. Thanks @yashints !

**Comment by yashints** [comment]
someone need to review it so I can complete it...

**Comment by petender** [comment]
I should have time tomorrow to close/check on some PRs and issues

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Review by fimdim — COMMENTED** [review]
Thanks @yashints !

**Review by petender — APPROVED** [review]

**Comment by petender** [comment]
thanks @yashints , approved, merged and cleaned up the branch.

**Review by lauraAlvEl — COMMENTED** [review]
Looks good to me. No comments from my end.

**Pull request merged**
