### PR TITLE
Update AZ400_M10_Controlling_Deployments_using_Release_Gates.md

### PR DESCRIPTION
**Pull request by cdanvergara**
Removing the comments '' on some commands, that is causing trouble while using the typing feature on the LODS lab environment.

# Module: 10
## Lab/Demo: Lab: Controlling Deployments using Release Gates

Fixes # .
Extra comments on the instructions need to be cleared out before actually running the commands on Azure CLI.

Changes proposed in this pull request:

- Removed the extra comments on the commands

### CODE REVIEW

**Comment by polichtm** [comment]
Hi Cristian,
would you mind clarifying what specific issue you are referring to?
Doesn't the original formatting match the one used on all AZ labs?
rgds
Marcin

**Comment by mkennten** [comment]
Please reject this PR, as it is an issue with Markdown in this particular lab. It's not about the backticks for the bash commands it's because of an issue that is introduced above. All other labs and even within this lab are displayed correctly.

image

Unai will provide a fix for the Markdown issue.

**Comment by unaihuete93** [comment]
the attached way it would work **Try preview in comment**, the ``` are needed for easy copy/pasting if I am not wrong:

1.  From the **Bash** prompt, in the **Cloud Shell** pane, run the following command to create a resource group (replace the `<region>` placeholder with the name of the Azure region that will host the two Azure web apps, for example 'westeurope' or 'eastus'):

    ```bash
    RESOURCEGROUPNAME='az400m10l01-RG'
    az group create -n $RESOURCEGROUPNAME -l '<region>'
    ```

    > **Note**: possible locations can be found by running the following command, use the **Name** on `<region>` : `az account list-locations -o table`

    

1.  To create an App service plan
   
    ```bash
    SERVICEPLANNAME='az400m01l01-sp1'
    az appservice plan create -g $RESOURCEGROUPNAME -n $SERVICEPLANNAME --sku S1
    ```
1.  Create two web apps with unique app names.
 
     ```bash
     SUFFIX=$RANDOM$RANDOM
     az webapp create -g $RESOURCEGROUPNAME -p $SERVICEPLANNAME -n PU$SUFFIX-Canary
     az webapp create -g $RESOURCEGROUPNAME -p $SERVICEPLANNAME -n PU$SUFFIX-Prod
     ```

**Comment by mkennten** [comment]
I'm closing this because I did not get a response from the requestor and fixed the issue in PR #30

**Pull request closed without merging**
