### PR TITLE
Lab1 with images proposal

### PR DESCRIPTION
**Pull request by unaihuete93**
# Module: 01
## Lab/Demo: 01

Changes proposed in this pull request:

- Adding images to the lab to reduce complexity on following instructions
-
-

### CODE REVIEW

**Review by krasmuss — CHANGES_REQUESTED** [review]
Can you add the Alt+Text for these images?

**Comment by unaihuete93** [comment]
ALt+Text added to images :)

**Comment by unaihuete93** [comment]
> Can you add the Alt+Text for these images?

ALT+Text added to images :)

**Comment by krasmuss** [comment]
Adding images

**Comment by krasmuss** [comment]
images added

**Pull request merged**
