### PR TITLE
M05-Lab05: Updated Lab 5 instructions

### LINKED ISSUE #172: M5-LAB05: The instruction is missing a step
### Contact Details

yasa@microsoft.com

### What happened?

Exercise : 02
Task: 02
Step: 01

Description of issue: The instruction is missing a step which confuses the students

Repro steps:
1. Open lab 5
1. Navigate to Ex 2 - Task 2 - Step 1
1. The step is missing the step to click on the security menu

### Lab

Lab 05 Configuring Agent Pools and Understanding Pipeline Styles

### Relevant screenshots

image

### Do you want to help us? 👏

- [X] I agree to follow this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

### PR DESCRIPTION
**Pull request by yashints**
Updated lab 5 instructions to include clicking on the security menu in the instructions which confuses students. Also added a missing step in self hosted agent configuration

## Related Issue

**Link related Github Issue** 🢂 Fixes #172 

## Checklist 
Mark completed with "x" between brackets, "[x]", or checking the box once the PR is created:
- [x] Has related GitHub Issue 💥 [Create Issue](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#reporting-issues) 📝
- [x] Tested it
- [x] Read the PR collaboration guide 👓 [Collaboration Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#pull-requests) 📝

Changes proposed in this pull request:

- Added a step so that students know they have to click on the security menu from the dropdown before accessing personal access token option
- Added a missing step in setting up self hosted agent

### CODE REVIEW

**Comment by unaihuete93** [comment]
Hi @yashints :) I cannot see the security option 
image
I only see it once a click on PAT, clicking Users Settings icon just shows the options on the screenshot

**Comment by yashints** [comment]
@unaihuete93  Seems like there are two flavours of menus available

menu

my students were seeing my version yesterday. Maybe we need to add both?

**Comment by yashints** [comment]
@unaihuete93 updated the instructions to include both scenarios

**Comment by unaihuete93** [comment]
looks great! :) approved! thanks for you help @yashints ❤️

**Pull request merged**
