### PR TITLE
LAB13: Instructions updates (Exercise 1, Task 2, Steps 4,5,7,10)

### PR DESCRIPTION
**Pull request by v-asamim**
LAB01: Extra-Character

**Replace issue name LAB00:QUICK_DESCRIPTION, for example "LAB01: My new issue" (or same name as linked Issue)**

## Related Issue

**Link related Github Issue** 🢂 Fixes # . (Include issue number after #)

## Checklist 
Mark completed with "x" between brackets, "[x]", or checking the box once the PR is created:
- [ ] Has related GitHub Issue 💥 [Create Issue](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#reporting-issues) 📝
- [ ] Tested it
- [ ] Read the PR collaboration guide 👓 [Collaboration Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#pull-requests) 📝

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Review by v-asamim — COMMENTED** [review]
Issue: M00-LAB13: Instructions 
need some updates #307 
Link: https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/issues/307

**Comment by unaihuete93** [comment]
@LuizMacedo I approve it until the lab13 renewal is published, what do you think?

**Comment by unaihuete93** [comment]
@LuizMacedo should we merge it, as the lab renewal may take a few weeks to be released?

**Comment by LuizMacedo** [comment]
@unaihuete93 definitely! Thank you @v-asamim!

**Comment by v-asamim** [comment]
> Great suggestions. Thank you!

you are welcome :)

**Pull request merged**
