### PR TITLE
Update AZ400_M03_L07_Implementing_GitHub_Actions_for_CI_CD.md

### LINKED ISSUE #403: M03-LAB07: Missing resource provider
### Contact Details

_No response_

### What should we change?

Add a step to register the Microsoft.Web resource provider

### Lab

Lab 07 Implementing GitHub Actions by using DevOps Starter

### Relevant screenshots

paste here 😉

### PR DESCRIPTION
**Pull request by yashints**
Added a step to register the resource provider for the subscription

**Replace issue name LAB00:QUICK_DESCRIPTION, for example "LAB01: My new issue" (or same name as linked Issue)**

## Related Issue

**Link related Github Issue** 🢂 Fixes #403  . (Include issue number after #)

## Checklist 
Mark completed with "x" between brackets, "[x]", or checking the box once the PR is created:
- [x] Has related GitHub Issue 💥 [Create Issue](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#reporting-issues) 📝
- [x] Tested it
- [x] Read the PR collaboration guide 👓 [Collaboration Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#pull-requests) 📝

Changes proposed in this pull request:

- Added a step to add the missing resource provider for app services
-
-

### CODE REVIEW

**Comment by unaihuete93** [comment]
@petender @fimdim @lauraAlvEl this change proposed by Yas, would be needed for any lab using WebApp, but it only happens to those students using Skillable as cloud platform. Not sure you want to include as part of this lab, or maybe part of Lab00 or Azure Pass subscription steps.

**Comment by fimdim** [comment]
@unaihuete93 I would suggest to keep it in each lab for now.

**Comment by yashints** [comment]
@unaihuete93 I really like the idea of putting it in the lab 000, makes all the labs consistent and you don't have to repeat the step

**Review by fimdim — COMMENTED** [review]
Thanks @yashints !

**Review by lauraAlvEl — COMMENTED** [review]
image

Line 108: This is a long sentence. I recommend adding a comma after the word "away".

**Comment by lauraAlvEl** [comment]
> @petender @fimdim @lauraAlvEl this change proposed by Yas, would be needed for any lab using WebApp, but it only happens to those students using Skillable as cloud platform. Not sure you want to include as part of this lab, or maybe part of Lab00 or Azure Pass subscription steps.

I wou

**Pull request closed without merging**
